### ISSUE TITLE
Any utility in unzipper?

### ISSUE THREAD

**Issue by muschellij2** [pamelarussell/TCIApathfinder#2]
I've used this in the past to download the file to a temporary area, and unzip the contents to a temporary area.  Utility in a PR for this?

```r
download_unzip_series = function(series_instance_uid,
                                 verbose = TRUE) {
  tdir = tempfile()
  dir.create(tdir, recursive = TRUE)
  tfile = tempfile(fileext = ".zip")
  tfile = basename(tfile)
  if (verbose) {
    message("Downloading Series")
  }
  res =  TCIApathfinder::save_image_series(
    series_instance_uid = series_instance_uid, 
    out_dir = tdir, 
    out_file_name = tfile)
  if (verbose) {
    message("Unzipping Series")
  }  
  stopifnot(file.exists(res$out_file))
  tdir = tempfile()
  dir.create(tdir, recursive = TRUE)
  res = utils::unzip(zipfile = res$out_file  , exdir = tdir)
  L = list(files = res,
           dirs = unique(dirname(normalizePath(res))))
  return(L)
}
```

Also open to an `unzip_image_series` or `extract_image_series` that takes in either a `series_instance_uid` or a result from `save_image_series`
```r
extract_image_series = function(series_result) {
  tdir = tempfile()
  dir.create(tdir, recursive = TRUE)
  res = utils::unzip(zipfile = series_result$out_file, exdir = tdir)
  L = list(files = res,
           dirs = unique(dirname(normalizePath(res))))
  return(L)
}
```

**Comment by pamelarussell** [comment]
Thanks John, I can see utility for both of these.

Would it make sense to slightly modify `download_unzip_series` to take an optional output directory in case users want to keep the files? I know the main use case would be to use and discard the files, but it might seem odd to force that behavior.

We can also include `extract_image_series` with the same comment about adding an optional explicit directory, and then we could call `extract_image_series` from within `download_unzip_series`. 

Does that all make sense? Thanks again for your contributions!

**Comment by pamelarussell** [comment]
Closing and moving discussion to https://github.com/pamelarussell/TCIApathfinder/pull/3.
